import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, Main } from '../components/sharedStyles';

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Agustines - Indumentaria</title>
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT"
          crossOrigin="anonymous"
        ></link>
      </Head>
      <Main></Main>
    </Container>
  );
};

export default Home;
